from django.urls import path

from . import views

app_name = 'inventory'
urlpatterns = [
    path('assettypes/',
         views.AssetTypesIndexView.as_view(), name='index_assettypes'),
    path('assettypes/create/',
         views.AssetTypeCreateView.as_view(), name='create_assettype'),
    path('assettypes/update/<int:pk>',
         views.AssetTypeUpdateView.as_view(), name='update_assettype'),
    path('assettypes/read/<int:pk>',
         views.AssetTypeReadView.as_view(), name='read_assettype'),
    path('assettypes/delete/<int:pk>',
         views.AssetTypeDeleteView.as_view(), name='delete_assettype'),


    path('featured/',
         views.AssetsFeaturedIndexView.as_view(), name='index_featured_assets'),
    path('featured/read/<int:pk>',
         views.AssetFeaturedReadView.as_view(), name='read_featured_asset'),

    path('assets/',
         views.AssetsIndexView.as_view(), name='index_assets'),
    path('assets/create/',
         views.AssetCreateView.as_view(), name='create_asset'),
    path('assets/update/<int:pk>',
         views.AssetUpdateView.as_view(), name='update_asset'),
    path('assets/read/<int:pk>',
         views.AssetReadView.as_view(), name='read_asset'),
    path('assets/delete/<int:pk>',
         views.AssetDeleteView.as_view(), name='delete_asset'),

    path('reservations/',
         views.ReservationsIndexView.as_view(), name='index_reservations'),
    path('reservations/create/',
         views.ReservationCreateView.as_view(), name='create_reservation'),
    path('reservations/update/<int:pk>',
         views.ReservationUpdateView.as_view(), name='update_reservation'),
    path('reservations/edit/<int:pk>',
         views.ReservationEditView.as_view(), name='edit_reservation'),
    path('reservations/read/<int:pk>',
         views.ReservationReadView.as_view(), name='read_reservation'),
    path('reservations/delete/<int:pk>',
         views.ReservationDeleteView.as_view(), name='delete_reservation'),
    path('reservations/addbasket/<int:pk>',
         views.ReservationAddBasket.as_view(), name='add_basket_reservation'),
    path('reservations/addbasket/',
         views.add_basket, name='add_basket'),
    path('reservations/clearreservedassets/',
         views.clear_reserved_assets, name='clear_reserved_assets'),
    path('reservations/deletereservedasset/',
         views.delete_reserved_asset, name='delete_reserved_asset'),

    path('reservedassets/',
         views.ReservedAssetsIndexView.as_view(), name='index_reservedassets'),
    path('reservedassets/create/',
         views.ReservedAssetCreateView.as_view(), name='create_reservedasset'),
    path('reservedassets/update/<int:pk>',
         views.ReservedAssetUpdateView.as_view(), name='update_reservedasset'),
    path('reservedassets/read/<int:pk>',
         views.ReservedAssetReadView.as_view(), name='read_reservedasset'),
    path('reservedassets/delete/<int:pk>',
         views.ReservedAssetDeleteView.as_view(), name='delete_reservedasset'),

    path('loanedassets/',
         views.LoanedAssetsIndexView.as_view(), name='index_loanedassets'),
    path('loanedassets/create/',
         views.LoanedAssetCreateView.as_view(), name='create_loanedasset'),
    path('loanedassets/update/<int:pk>',
         views.LoanedAssetUpdateView.as_view(), name='update_loanedasset'),
    path('loanedassets/read/<int:pk>',
         views.LoanedAssetReadView.as_view(), name='read_loanedasset'),
    path('loanedassets/delete/<int:pk>',
         views.LoanedAssetDeleteView.as_view(), name='delete_loanedasset'),

    path('returnedassets/',
         views.ReturnedAssetsIndexView.as_view(), name='index_returnedassets'),
    path('returnedassets/create/',
         views.ReturnedAssetCreateView.as_view(), name='create_returnedasset'),
    path('returnedassets/update/<int:pk>',
         views.ReturnedAssetUpdateView.as_view(), name='update_returnedasset'),
    path('returnedassets/read/<int:pk>',
         views.ReturnedAssetReadView.as_view(), name='read_returnedasset'),
    path('returnedassets/delete/<int:pk>',
         views.ReturnedAssetDeleteView.as_view(), name='delete_returnedasset'),

]
