# Generated by Django 2.1.8 on 2019-05-29 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('town', models.CharField(blank=True, max_length=48)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('fax_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('url', models.URLField(blank=True, max_length=128)),
                ('info', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='nations.Country')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_supplier_related', related_query_name='market_suppliers', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markets_supplier_related', related_query_name='market_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
