# Generated by Django 2.1.8 on 2019-05-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
