# Generated by Django 2.1.8 on 2019-05-27 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('shortcut', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('info', models.TextField(blank=True)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_assettype_related', related_query_name='inventory_assettypes', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorys_assettype_related', related_query_name='inventory_assettypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asset Types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LoanedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('info', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_loanedasset_related', related_query_name='inventory_loanedassets', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorys_loanedasset_related', related_query_name='inventory_loanedassets', to=settings.AUTH_USER_MODEL)),
                ('receiver_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanedasset_receiver_out', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Loaned Assets',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_consumer', to=settings.AUTH_USER_MODEL)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservation_related', related_query_name='inventory_reservations', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorys_reservation_related', related_query_name='inventory_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='ReservedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('info', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Asset')),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservedasset_related', related_query_name='inventory_reservedassets', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorys_reservedasset_related', related_query_name='inventory_reservedassets', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Reservation')),
            ],
            options={
                'verbose_name_plural': 'Reserved Assets',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReturnedAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('deliver_date', models.DateField(blank=True, null=True)),
                ('deliver_time', models.TimeField(blank=True, null=True)),
                ('info', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('created_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_returnedasset_related', related_query_name='inventory_returnedassets', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorys_returnedasset_related', related_query_name='inventory_returnedassets', to=settings.AUTH_USER_MODEL)),
                ('loanedasset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.LoanedAsset')),
                ('receiver_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returnedasset_receiver_in', to=settings.AUTH_USER_MODEL)),
                ('supplier_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returnedasset_supplier_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Returned Assets',
            },
        ),
        migrations.AddField(
            model_name='loanedasset',
            name='reservedasset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.ReservedAsset'),
        ),
        migrations.AddField(
            model_name='loanedasset',
            name='supplier_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanedasset_supplier_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='assettype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_type', to='inventory.AssetType'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_asset_related', related_query_name='inventory_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_modified_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventorys_asset_related', related_query_name='inventory_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
