# Generated by Django 2.1.8 on 2019-06-03 07:01

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190603_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.upload_assets_image_path),
        ),
        migrations.AddField(
            model_name='asset',
            name='lemma',
            field=models.TextField(blank=True),
        ),
    ]
