# Generated by Django 2.1.8 on 2019-06-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190603_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='slug',
            field=models.SlugField(default='abc'),
            preserve_default=False,
        ),
    ]
