# Generated by Django 2.1.8 on 2019-06-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_asset_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
