# Generated by Django 2.2.3 on 2019-07-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['room'], 'verbose_name_plural': 'Locations'},
        ),
    ]
